# SPDX-FileCopyrightText: 2025 Ryan Stocks <ryan.stocks00@gmail.com>
# SPDX-License-Identifier: MIT
---
# This file configures https://pre-commit.com/
repos:
  - repo: https://github.com/cheshirekow/cmake-format-precommit
    rev: v0.6.13
    hooks:
      - id: cmake-format
        name: CMake Format
        entry: cmake-format
      - id: cmake-lint
        name: CMake Lint
        entry: cmake-lint
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v20.1.8
    hooks:
      - id: clang-format
  - repo: https://github.com/google/yamlfmt.git
    rev: v0.17.2
    hooks:
      - id: yamlfmt
        args: ["-conf", ".yamlfmt"]
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-shebang-scripts-are-executable
      - id: check-executables-have-shebangs
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=100']
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: name-tests-test
  - repo: https://github.com/crate-ci/typos
    rev: v1.19.0
    hooks:
      - id: typos
        args: ['--write-changes']
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: ['--fix']
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.20.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        name: "Insert license header in C++ files"
        args:
          - "--detect-license-in-X-top-lines=5"
          - "--license-filepath=license_header.txt"
          - "--comment-style=/*| *| */"
          - "--use-current-year"
        types_or: [c++]
      - id: insert-license
        name: "Insert license header in txt files"
        args:
          - "--detect-license-in-X-top-lines=5"
          - "--license-filepath=license_header.txt"
          - "--use-current-year"
        files: \.txt$|\.cmake$|\.yml$|\.yaml$|\.sh$|\.gitignore$|.clang-format$
        exclude: license_header.txt|LICENSES/.*|LICENSE*
      - id: insert-license
        name: "Insert license header in md files"
        args:
          - "--detect-license-in-X-top-lines=5"
          - "--license-filepath=license_header.txt"
          - "--use-current-year"
          - "--comment-style=<!--| | -->"
        files: \.md$
        repos:
  - repo: https://github.com/fsfe/reuse-tool
    rev: v5.0.2
    hooks:
      - id: reuse
